### ISSUE TITLE
To Do before workshop

### ISSUE THREAD

**Issue by tavareshugo** [tavareshugo/2019-01-29-EMBL#1]
Some things to do before workshop:

- [x] Ensure software is installed in training machines (see [setup instructions](https://tavareshugo.github.io/2019-01-29-EMBL/#setup))

- [x] Send [carpentries pre-workshop survey](https://www.surveymonkey.com/r/dcpreworkshopassessment?workshop_id=2019-01-29-EMBL) to participants?

- [x] Print `base R`, `tidyr`, `dplyr` and `ggplot2` cheatsheets? ([here](https://github.com/rstudio/cheatsheets/raw/master/base-r.pdf), [here](https://github.com/rstudio/cheatsheets/raw/master/data-import.pdf), [here](https://github.com/rstudio/cheatsheets/raw/master/data-transformation.pdf) and [here](https://github.com/rstudio/cheatsheets/raw/master/data-visualization-2.1.pdf))

**Comment by FloHu** [comment]
I also found the [base R](http://github.com/rstudio/cheatsheets/raw/master/base-r.pdf) cheatsheet quite useful.

**Comment by tavareshugo** [comment]
Also note I've added a section called "further resources", where there's a document with [`dplyr` - `base R` equivalents](https://tavareshugo.github.io/data_carpentry_extras/base-r_tidyverse_equivalents/base-r_tidyverse_equivalents.html)

**Comment by tobyhodges** [comment]
Points 1 & 3 are ✅

**Comment by tobyhodges** [comment]
Point 2 is done now too, though I still need to send the pre-workshop survey to a few last-minute additions.
